let state=Store.load(), page=state.page||'dashboard';
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function card(h){return `<section class="card">${h}</section>`} function save(){Store.save(state)} function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
function setPage(p){page=p;state.page=p;save();render()}
function dashboard(){const s=Engine.sessionFor(state),a=Engine.adapt(state),r=Engine.readiness(state);return `<div class="page"><div class="hero"><div class="eyebrow">TACTICAL PROGRAMMER</div><h2>Hybrid / Operator</h2><p class="muted">Indefinite baseline. The engine adjusts around reality instead of pretending your calendar is the boss.</p><div class="row"><span class="pill accent">Week ${s.week}</span><span class="pill">${state.detour?state.detour.type+' detour':'Baseline'}</span></div></div><div class="grid">${card(`<div class="stat">${esc(s.title)}</div><div class="label">Today</div>`)}${card(`<div class="stat">${r.score??'—'}</div><div class="label">Readiness</div>`)}</div>${card(`<div class="between"><b>Decision engine</b><span class="pill ${a.status==='stable'?'good':'accent'}">${a.status}</span></div><p class="muted small">${esc(a.reason)} — ${esc(a.message)}</p>`)}${card(`<div class="between"><div><b>Next session</b><div class="muted small">${esc(s.subtitle)}</div></div><button class="btn" data-go="today">Open</button></div>`)}${card(`<b>Current rules</b><ul class="muted small"><li>Baseline is Hybrid/Operator.</li><li>Detours are temporary and have an exit.</li><li>Actual performance and readiness influence the next decision.</li></ul>`)}</div>`}
function programme(){let h='';for(let i=1;i<=14;i++){const w=Programme.blockWeek(i),p=Programme.hybridOp[w-1];h+=`<div class="week"><div class="weekhead">Week ${i} <span>cycle ${w}</span></div><div class="days">${p.map((x,j)=>`<div class="day ${Programme.classify(x)}"><strong>${['M','T','W','T','F','S','S'][j]}</strong>${esc(x)}</div>`).join('')}</div></div>`}return `<div class="page"><div class="hero"><div class="eyebrow">BASELINE</div><h2>Programme</h2><p class="muted">The GP Hybrid/Op baseline is a repeating framework; it is intentionally customizable rather than a fixed annual calendar.</p></div><div class="timeline">${h}</div>${card(`<b>Operator wave</b><p class="muted small">${Programme.operatorWave.map(x=>`${x.pct}%`).join(' → ')}. Minimum sets are used first; volume can increase when recovery supports it.</p>`)}</div>`}
function today(){const s=Engine.sessionFor(state);return `<div class="page"><div class="hero"><div class="eyebrow">${s.date}</div><h2>${esc(s.title)}</h2><p class="muted">${esc(s.subtitle)}</p></div>${card(s.items.length?s.items.map(x=>`<div class="exercise"><span>${esc(x.name)}</span><b>${esc(x.detail)}</b></div>`).join(''):`<div class="empty">Recovery day.</div>`)}${s.type==='strength'?card(`<h3>Record actual work</h3><form id="sessionForm" class="form"><label>Status<select name="status"><option value="completed">Completed</option><option value="modified">Modified</option><option value="missed">Missed</option></select></label><label>Session RPE<input name="rpe" type="number" min="1" max="10" value="7"></label><label class="check"><input name="pain" type="checkbox"> Pain / recovery issue</label><label>Notes<textarea name="notes" rows="3"></textarea></label><button class="btn">Save session</button></form>`):card(`<div class="row"><button class="btn" data-log="completed">Log completed</button><button class="btn secondary" data-log="missed">Log missed</button></div><p class="muted small">Use Reality for detailed readiness or modifications.</p>`) }${card(`<button class="btn secondary" data-go="reality">Reality / readiness</button>`)}</div>`}
function reality(){const last=state.readiness.at(-1)||{};return `<div class="page"><div class="hero"><div class="eyebrow">REALITY ENGINE</div><h2>Tell it how you actually are.</h2><p class="muted">1–5 scales: sleep and motivation high is good; soreness and stress high is bad.</p></div>${card(`<form id="readinessForm" class="form"><label>Sleep quality (1–5)<input name="sleep" type="number" min="1" max="5" value="${last.sleep||3}"></label><label>Soreness (1–5)<input name="soreness" type="number" min="1" max="5" value="${last.soreness||2}"></label><label>Stress (1–5)<input name="stress" type="number" min="1" max="5" value="${last.stress||2}"></label><label>Motivation (1–5)<input name="motivation" type="number" min="1" max="5" value="${last.motivation||3}"></label><button class="btn">Update readiness</button></form>`)}${card(state.detour?`<div class="between"><b>Active ${esc(state.detour.type)} detour</b><button class="btn danger" data-end-detour="1">Return to baseline</button></div><p class="muted small">${state.detour.week} / ${state.detour.length} weeks used.</p>`:`<b>Start a deliberate detour</b><p class="muted small">Choose an emphasis only when there is a reason.</p><div class="row">${['SE','STRENGTH','RUCK','RUNNING'].map(x=>`<button class="btn secondary" data-detour="${x}">${x}</button>`).join('')}</div>`)}</div>`}
function library(){return `<div class="page"><div class="hero"><div class="eyebrow">TRAINING VAULT</div><h2>HIC + SE</h2><p class="muted">Selection metadata for rotation. The engine avoids reproducing copyrighted source text.</p></div>${card(`<h3>HIC</h3>${Library.hic.map(x=>`<div class="exercise"><span>${esc(x.name)}<small class="muted"> · ${esc(x.modality)}</small></span><span class="pill">${esc(x.impact)}</span></div>`).join('')}`)}${card(`<h3>SE</h3>${Library.se.map(x=>`<div class="exercise"><span>${esc(x.name)}<small class="muted"> · ${esc(x.stimulus)}</small></span><span class="pill">${esc(x.impact)}</span></div>`).join('')}`)}</div>`}
function athlete(){return `<div class="page"><div class="hero"><div class="eyebrow">ATHLETE</div><h2>Profile</h2></div>${card(`<form id="athleteForm" class="form">${Programme.lifts.map(l=>`<label>${l.name}<input name="${l.id}" type="number" step="0.5" value="${state.maxes[l.id]}"></label>`).join('')}<label>Training days<select name="days" multiple>${['M','T','W','T','F','S','S'].map((x,i)=>`<option value="${i}" ${state.trainingDays.includes(i)?'selected':''}>${x}</option>`).join('')}</select></label><button class="btn">Save profile</button></form>`)}${card(`<button class="btn danger" data-reset="1">Reset app</button>`)}</div>`}
function render(){const titles={dashboard:'Dashboard',programme:'Programme',today:'Today',reality:'Reality',library:'Library',athlete:'Athlete'};$('#pageTitle').textContent=titles[page];$('#app').innerHTML={dashboard,programme,today,reality,library,athlete}[page]();document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.page===page));
 document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>setPage(x.dataset.go));document.querySelectorAll('[data-log]').forEach(x=>x.onclick=()=>logQuick(x.dataset.log));document.querySelectorAll('[data-detour]').forEach(x=>x.onclick=()=>startDetour(x.dataset.detour));document.querySelectorAll('[data-end-detour]').forEach(x=>x.onclick=()=>{state.detour=null;save();toast('Back to baseline');render()});document.querySelectorAll('[data-reset]').forEach(x=>x.onclick=()=>Store.reset());
 const sf=$('#sessionForm');if(sf)sf.onsubmit=e=>{e.preventDefault();const f=new FormData(sf);commitSession({status:f.get('status'),rpe:f.get('rpe'),pain:f.get('pain')==='on',notes:f.get('notes')})};
 const rf=$('#readinessForm');if(rf)rf.onsubmit=e=>{e.preventDefault();const f=new FormData(rf);state.readiness.push({date:Engine.dateKey(),sleep:+f.get('sleep'),soreness:+f.get('soreness'),stress:+f.get('stress'),motivation:+f.get('motivation')});save();toast('Readiness updated');render()};
 const af=$('#athleteForm');if(af)af.onsubmit=e=>{e.preventDefault();const f=new FormData(af);Programme.lifts.forEach(l=>state.maxes[l.id]=+f.get(l.id));state.trainingDays=[...af.querySelector('[name=days]').selectedOptions].map(o=>+o.value);save();toast('Profile saved');render()};}
function commitSession(r){const s=Engine.sessionFor(state);Engine.logResult(state,s,r);save();toast('Session logged');render()}
function logQuick(status){commitSession({status,rpe:status==='completed'?7:0,pain:false,notes:''})}
function startDetour(type){const lengths={SE:4,STRENGTH:3,RUCK:4,RUNNING:4};state.detour={type,length:lengths[type]||4,week:1,started:Engine.dateKey()};save();toast(type+' detour started');setPage('today')}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setPage(b.dataset.page));document.body.insertAdjacentHTML('beforeend','<div id="toast" class="toast"></div>');render();
